### ISSUE TITLE
Minor Issue --- CSS for scroll bars on hover ...

### ISSUE THREAD

**Issue by TiddlyTweeter** [wikilabs/plugins#110]
Your CSS plugin at https://wikilabs.github.io/editions/thin-scrollbars/ is useful! Simple. Does the job!

There is _one minor issue_ for the right sidebar on hover when there are many items. Here is a screen shot where the "inner" scrollbar goes back to "fat" on hovering the sidebar ... 

![Screenshot 2021-12-27 075324](https://user-images.githubusercontent.com/28830541/147443966-b18ebcfc-0bfc-4a17-a050-e6882abcc3fd.jpg)

I'm not sure if this is solvable???

Just a comment. 
TT.

**Comment by pmario** [comment]
>Here is a screen shot where the "inner" scrollbar goes back to "fat" on hovering the sidebar ...

That's intentional. It makes it easier to "catch" it with the mouse. 

See: https://wikilabs.github.io/editions/thin-scrollbars/#%24%3A%2Fplugins%2Fwikilabs%2Fthin-scrollbars%2Fstyles ... the `:hover` CSS is responsible for this. ... If you want a different behaviour, it's probably better to remove the plugin and copy the CSS elements you want. ... There will be less overhead ;)

**Comment by TiddlyTweeter** [comment]
> That's intentional. It makes it easier to "catch" it with the mouse and it makes it visible, which bar is for which element.

Ah! Thanks. That is useful information! I'll close the issue.
