### ISSUE TITLE
Minor BUG? - Repeated Styles Inserted Into Tag IF `ID` has `symbol` AND  `_classes=` not set

### ISSUE THREAD

**Issue by pmario** [wikilabs/plugins#64]
### Minor BUG? - Repeated Styles Inserted Into Tag IF `ID` has `symbol` AND  `_classes=` not set

IF you assign a "symbol" to an ID but leave `_classes=` UNdefined then styles get REPEATED IF you enter them from text. That does NOT happen if you create _classes= in the pragma.

This shows the issue: `/°TEST.repeated-style appears twice °/`

... customise ...

```
\customise slash=TEST 
```
... render ...

```
<p>This shows the issue: <span class="repeated-style repeated-style wltc-inline wltc">appears TWICE</span></p>
```

_Originally posted by @TiddlyTweeter in https://github.com/wikilabs/plugins/discussions/62#discussioncomment-376204_

**Comment by TiddlyTweeter** [comment]
Ciao PMario, I notice you updated and the "repeated class" problem is gone. 
But it looks like a different one now happens. It happens when you make a pragma without a "_classes=" set  (not empty, just not present) ... you can see the issue below ... 

```
\customise angle=SYM _element=p _classes=""

»SYM.test
```

Result ..., OK
`<p class="test wltc-l1 wltc"></p>`


```
\customise angle=SYM _element=p 

»SYM.test
```

Result, "**undefined**" class is added and appended to "test" class :-(.
`<p class="testundefined wltc-l1 wltc"></p>`

**Comment by pmario** [comment]
Sorry! Bad testing. Next version will fix it soon!
